---
title: "tSNE of wastewater virome communities by site, city, and date"
output: html_notebook
---

load packages
```{r}
library(ggplot2)
library(data.table)
library(stringr)
library(dplyr)
library(lubridate)
library(tidyr)
library(rprojroot)
library(Rtsne)
library(wesanderson)
library(cowplot)

```

set paths and filenames
```{r}
### files
virome_table=sprintf(
  "%s/data/wastewater_virome_abundance_table1.tsv", 
  find_rstudio_root_file())
metadata_table=sprintf(
  "%s/data/wastewater_sample_metadata_table1.tsv", 
  find_rstudio_root_file())

```

load virome table, make wide
```{r}
virome_dt <- fread(virome_table, sep = "\t", header = T )
meta_dt <- fread(metadata_table, sep = "\t", header = T )

seqname_sID_wide_dt <- 
  virome_dt %>% 
  subset(select = c("sequence_name", "sample_ID", "RPKMF")) %>%
  distinct(sequence_name, sample_ID, RPKMF) %>%
  pivot_wider(names_from = sequence_name, values_from = RPKMF, values_fill = 0)

sampleID_l <- seqname_sID_wide_dt$sample_ID

seqname_sID_wide_dt <- seqname_sID_wide_dt %>% subset(select = -sample_ID)
```

make tSNE data structure
```{r}

tephi_prcomp1 <- prcomp(log10(seqname_sID_wide_dt+1))

emb <- Rtsne::Rtsne(tephi_prcomp1$x[,1:10])

embb <- emb$Y

rownames(embb) <- sampleID_l

embb_df <- as.data.frame(embb)

embb_dt <- setDT(embb_df, keep.rownames = "sample_ID")

embb_dt <- merge(embb_dt, meta_dt, by ="sample_ID")

embb_dt$City_Site <- str_c(embb_dt$City, ", ", embb_dt$Site)

embb_dt$Date <- as.Date(embb_dt$Date, , "%m-%d-%Y")

```

plot tSNE
```{r}
pal <- wes_palette("Zissou1", 2, type = "continuous")

city_tsnep <- embb_dt %>%
  ggplot(aes(x=V1, y=V2, color=City, shape = City_Site)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_shape_manual(values=c(15, 16, 17, 18, 3, 4 ,8, 9, 11, 13))+
  scale_color_manual(values = pal) +
  theme_bw() +
  labs(x="tSNE-1", y="tSNE-2")

city_tsnep


as.Date_origin <- function(x){
  as.Date(x, origin = '1970-01-01')
}
date_tsnep <- embb_dt %>%
  ggplot(aes(x=V1, y=V2, color=as.integer(Date), shape = City)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_gradient(low = "#FDD262",
  high = "#3F3F7B", labels=as.Date_origin, name = "Date") +
  theme_bw() +
  labs(x="tSNE-1", y="tSNE-2")

date_tsnep

combp <- plot_grid(city_tsnep, date_tsnep, 
                   align = "h", nrow = 1, rel_widths = c(56/100, 44/100))

ggsave(combp, file = sprintf("%s/charts/tSNE_plots_city_date.pdf", find_rstudio_root_file()), width = 10, height = 4)
```








