---
title: "Houston & El Paso WWTP Service Areas"
output:
  html_notebook:
    toc: yes
date: "2023-03-16"
---

```{r setup, include=FALSE}  
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(rgdal)
library(readxl)
library(dplyr)
library(tmap)
library(sf)
library(ggplot2)
library(rgeos)
library(ggmap)
library(maptools)
library(gpclib)
```


### Houston Area
```{r message=FALSE}
# Read in WWTP shapefiles
shp <- readOGR("WWTP", "WW_Houston", verbose=F)
#shp <- read_sf("WWTP/WW_final.shp")
# subset the shapefiles of the 6 facilities with data
focus <- subset(shp, shp$CorName %in% c("Homestead", "Intercontinental Airport", "Park Ten", "Turkey Creek", "Almeda Sims", "Metro Central"))
# Get Harris County shapefiles 
county_shp <- tigris::counties(state = "TX", year=2021)
harris_shp <- subset(county_shp, county_shp$NAME=="Harris")
# map of the 39 facilities with the 6 highlighted 
tm_shape(harris_shp)+tm_borders("grey30", alpha=0.5)+
  tm_shape(shp)+ tm_borders("black", alpha=0.75)+
    tm_shape(focus) + tm_borders("red", alpha=1)
```

```{r}
## Read in the addresses of the Houston Wastewater facilities
address <- read_excel("WWTP_address.xlsx")
# address <- read_excel("(HOU) WWTP Address List.xlsx")
# address$City <- "Houston"
# address$coordinates <- geocode(address$Address)
# address$lat <- address$coordinates$lat; address$lon <- address$coordinates$lon
# address$lon[4] <- -95.62125471114265; address$lat[4] <- 29.76319241835248
# writexl::write_xlsx(address, "Processed_data/WWTP_address.xlsx")

# Harris Zipcode shapfile
zip <- readOGR("TexasZipcode", "TexasZipcode")
###### Harris county #########
# list of Zip Codes in Harris County
hzip <- read_excel("Harris_zipcodelist.xlsx")
hzip$zipcode <- substr(hzip$`ZIP Code`, 10,14)

# Match zipcodes with ZCTAs
zip$GEOID10 <- as.character(zip$GEOID10)
HarrisZip <- subset(zip, zip$GEOID10 %in% hzip$zipcode)

# convert to ggplot objects
gpclibPermit
gpclibPermitStatus = T
gpclibPermitStatus
ggHarris <- fortify(HarrisZip, region="GEOID10")
ggWW <- fortify(focus, region="FID_1")

# add locations 
coordinates <- address[,c("Sampling Site", "lat", "lon")]
coor_sf = st_as_sf(coordinates, coords = c('lon', 'lat'), crs = st_crs(HarrisZip)$proj4string)

# Harris county google map (Google API is needed)
Harris<- geocode("Harris county, TX")  #lon -97.5  lat 26.1
Harris_center <- c(-95.52, 29.8)
Harris_Map <- ggmap(get_googlemap(center=Harris_center, scale=2 ,zoom=9, maptype = "terrain"), extent="panel")
Harris_Map

```

#### Map of WWTP service areas overlayed with Harris County ZCTAs
```{r fig.height=5, fig.width=6}
focus = spTransform(focus, CRS("+init=epsg:4326"))

# m2<- tm_shape(HarrisZip)+ tm_borders("grey30", lwd=0.6)+
#   #tm_shape(shp)+ tm_polygons("grey30", alpha=0.5, border.col = "black", border.alpha = 1)+
#   tm_shape(focus) + tm_borders("red", alpha=1, lwd=1.5)+
#   tm_shape(coor_sf)+
#   tm_symbols(size=0.1, col="black", border.col="black")+tm_text("Sampling Site", size=1.2, just="left", ymod=0.6)+
#   tm_add_legend('symbol', col='black', border.col='black', size=0.3, title="WWTF locations") +
#   tm_add_legend('symbol', col='white', border.col='red', size=1, title="Service area") +
#   tm_add_legend('symbol', col='white', border.col='grey30', size=1, title="ZCTA boundaries") +
#   tm_layout(title="Harris County Zip Code Map overlayed with WWTF service areas",
#             inner.margins=c(0,0,0.05,0))

# Houston downtown
Houston<- geocode("Houston, TX")  #lon -97.5  lat 26.1
Houston_dt<- c("Houston", -95.4, 29.8) %>% t() %>%as.data.frame()

# add Zipcode marks
HarrisZip$lat <- as.numeric(as.character(HarrisZip$INTPTLAT10))
HarrisZip$lon <- as.numeric(as.character(HarrisZip$INTPTLON10))
coordinates1 <- HarrisZip@data[,c("GEOID10", "lat", "lon")]
coor_sf1 = st_as_sf(coordinates1, coords = c('lon', 'lat'), crs = st_crs(HarrisZip)$proj4string)

dt_coor <- st_as_sf(Houston_dt, coords=c("V2", "V3"),crs = st_crs(HarrisZip)$proj4string)

#focus$`Service Areas` <- focus$CorName
focus$`Service Areas` <- c("1","2","3","4","5","6")
m2<-  tm_shape(harris_shp)+ tm_polygons("grey30", alpha=0, border.col = "black", border.alpha = 1, lwd=2)+
  tm_shape(focus) + tm_fill(col="Service Areas", alpha=1, lwd=1.5)+ tm_symbols(size=2, col="white", border.col = "black")+
  tm_text("Service Areas", size=1)+
  #tm_shape(HarrisZip)+ tm_borders("grey30", lwd=1.5)+ #zipcode boundaries
  #tm_shape(coor_sf1)+tm_text("GEOID10", size=0.5)+ # mark zipcode
  tm_shape(dt_coor)+tm_symbols(size=0.5, col="black", border.col ="black")+tm_text("V1", size=1.5, just="bottom", ymod=1)+ # mark Houston Downtown
  tm_add_legend('symbol', col='black', border.col='black', size=0.5, 
                label="Houston downtown",
               legend.format = list(text.align = "left"),reverse = T) +
  #tm_add_legend('symbol', col='white', border.col='black', size=1.5, title="Harris County boundary") +
  tm_add_legend(type = c("line"),
                col = c("black"),
                lwd = c(2),
                lty = c(1),
                labels = c("Harris County boundary"),legend.format = list(text.align = "left"))+
  #tm_add_legend('symbol', col='white', border.col='grey30', size=1, title="Zip Code boundaries") +
  tm_layout(#title="Harris County",
            #scale=0.9,
            #inner.margins=c(0,0.1,0,0),
            #frame=F,
            legend.text.size = 1,
            legend.title.size=1)+
   tm_compass(position = c("right", "top"))+
  tm_scale_bar(position = c("left", "bottom"))
m2
# save the map
tmap_save(m2, "Houston_6WWTP_map.png", height=6, width=8,dpi=300)

m2<- tm_shape(HarrisZip)+ tm_borders("grey30", lwd=0.6)+
  #tm_shape(shp)+ tm_polygons("grey30", alpha=0.5, border.col = "black", border.alpha = 1)+
  tm_shape(focus) + tm_borders("red", alpha=1, lwd=1.5)+
  tm_shape(coor_sf)+
  tm_symbols(size=0.1, col="black", border.col="black") +
  tm_text("Sampling Site", size=1, just="left", ymod=0.6)+
  tm_add_legend('symbol', col='black', border.col='black', size=0.3, title="WWTF locations") +
  tm_add_legend('symbol', col='white', border.col='red', size=1, title="Service area") +
  tm_add_legend('symbol', col='white', border.col='grey30', size=1, title="ZCTA boundaries") #+
  #tm_layout(title="Harris County Zip Code Map overlayed with WWTF service areas",
  #          inner.margins=c(0,0,0.05,0))

m2
# save the map
tmap_save(m2, "Houston_6WWTP_map.pdf", width=6, height=4)



# Map with Google map background
m1 <- Harris_Map  +
  geom_polygon(data = ggHarris, aes(x=long, y=lat, group = group), color="grey50", size=0.7, alpha=0)+
  geom_polygon(data = ggWW, aes(x=long, y=lat, group = group), color="red", size=0.8, fill="pink")+
  xlab("Longitude")+ylab("Latitude")+labs(fill="")+
  geom_point(data=coordinates, aes(lon, lat), colour="black", size=1.5)+
  geom_text(data = coordinates, mapping = aes(x=lon, y=lat+0.01, label=`Sampling Site`), size=4, color="blue")+
  ggtitle("Harris County Zipcode Map overlayed with WWTF locations")+
  coord_fixed(xlim=c(-96.1,-94.85), ylim=c(29.45, 30.25))
m1
#save the map
#ggsave("Houston_6WWTP_map2.png",m1)

```


### El Paso
```{r fig.height=8, fig.width=6}
# Read in WWTP shapefiles
El_shp <- readOGR("WWTP", "WW_ElPaso", verbose=F)
# read in the list of Zipcodes in El Paso
# list of Zip Codes in Harris County
ezip <- read_excel("ElPaso_zipcodelist.xlsx")
# Match zipcodes with ZCTAs
ElPasoZip <- subset(zip, zip$GEOID10 %in% ezip$Zipcode)

#El_shp$`Service Areas` <- ifelse(El_shp$ServiceAre=="Bustamante", "Roberto Bustamante", ifelse(El_shp$ServiceAre=="Northwest", "John T. Hickerson", ifelse(El_shp$ServiceAre=="Hervey", "Fred Hervey", El_shp$ServiceAre)))
El_shp$`Service Areas` <- ifelse(El_shp$ServiceAre=="Bustamante", "3", ifelse(El_shp$ServiceAre=="Northwest", "1", ifelse(El_shp$ServiceAre=="Hervey", "2", "4")))

# add Zipcode marks
ElPasoZip$lat <- as.numeric(as.character(ElPasoZip$INTPTLAT10))
ElPasoZip$lon <- as.numeric(as.character(ElPasoZip$INTPTLON10))
coordinates2 <- ElPasoZip@data[,c("GEOID10", "lat", "lon")]
coor_sf2 = st_as_sf(coordinates2, coords = c('lon', 'lat'), crs = st_crs(ElPasoZip)$proj4string)

El_shp$"ID" <- c("3", "1", "2", "", "", "4", "", "", "", "", "")
# El Paso County
El_county <- subset(county_shp, county_shp$NAME=="El Paso")
# El Paso downtown
ElPaso<- geocode("El Paso, TX")  #lon -97.5  lat 26.1
ElPaso_dt<- c("El Paso", -106.4869, 31.7583) %>% t() %>%as.data.frame()
dt_coor2 <- st_as_sf(ElPaso_dt, coords=c("V2", "V3"),crs = st_crs(ElPasoZip)$proj4string)


El_shp2 <- subset(El_shp, El_shp$ID %in% c("1", "2", "3", "4"))

m3<-  tm_shape(El_county)+ tm_polygons("grey30", alpha=0, border.col = "black", border.alpha = 1, lwd=2)+
  tm_shape(El_shp) + tm_fill(col="Service Areas", alpha=1, lwd=1.5)+
  tm_shape(El_shp2)+ tm_symbols(size=2, col="white", border.col = "black")+ tm_text("ID", size=1)+
  #tm_shape(ElPasoZip)+ tm_borders("grey30", lwd=1.5)+
  #tm_shape(coor_sf2)+tm_text("GEOID10", size=0.8)+
  tm_shape(dt_coor2)+tm_symbols(size=0.5, col="black", border.col ="black")+tm_text("V1", size=1.5, just=c("right","bottom"), xmod=-1)+ # mark Downtown
  tm_add_legend('symbol', col='black', border.col='black', size=0.5, label="El Paso downtwon") +
  tm_add_legend(type = c("line"),
                col = c("black"),
                lwd = c(2),
                lty = c(1),
                labels = c("El Paso County boundary"),legend.format = list(text.align = "left"))+
  #tm_add_legend('symbol', col='white', border.col='grey30', size=1, title="Zip Code boundaries") +
  tm_layout(#title="EL Paso",
            #scale=0.8,
            #inner.margins=c(0,0,0,0.1),
            #frame=F,
            legend.text.size = 1,
            legend.title.size=1)+
  tm_compass(position = c("right", "top"), just = "Right")+
  tm_scale_bar(position = c("left", "bottom"))
m3
# save the map
tmap_save(m3, "ElPaso_4WWTP_map.png", height=6, width=8, dpi=300)

map <- tmap_arrange(m2,m3, nrow=1)
map
```


### Get ZCTA list (Houston)
```{r}
# Get the list ZCTAs within each WWTP service areas
proj4string(HarrisZip) <- proj4string(focus)
focus1 <- st_as_sf(focus)
HarrisZip1<- st_as_sf(HarrisZip)
focus1 <- st_transform(focus1, "+proj=longlat +datum=WGS84")
focus = spTransform(focus, CRS("+init=epsg:4326"))
st_crs(HarrisZip1) <- st_crs(focus1)

# Extract the ZCTAs within each WWTP and coverage areas (%):
service_area <- data.frame()
options(scipen=999)
# Calculate area and tidy up
for (area in focus$SERVICE_AR) {
  
intersect_pct <- st_intersection(HarrisZip1,subset(focus1, focus1$SERVICE_AR==area)) %>% 
   mutate(intersect_area = st_area(.)) %>%   # create new column with shape area
   dplyr::select(GEOID10, intersect_area) %>%   # only select columns needed to merge
   st_drop_geometry()  # drop geometry

# Create a fresh area variable for ZCTAs
HZ <- mutate(HarrisZip1, zcta_area = st_area(HarrisZip1))

# Merge by county name
HZ <- merge(HZ[,c("GEOID10", "zcta_area")], intersect_pct, by = "GEOID10", all.y = TRUE)

# Calculate coverage
HZ <- HZ %>% 
   mutate(coverage_pct = as.numeric(intersect_area/zcta_area*100), WWTP=area)

service_area <- rbind(service_area, HZ)

}

final <- service_area %>% 
  select(WWTP, GEOID10, coverage_pct) %>%
  st_drop_geometry() %>%
  rename(ZCTA=GEOID10) %>%
  filter(coverage_pct>=5)

final
```


```{r}
# Get ZCTA level population data
pop <- tidycensus::get_acs(geography = "zcta",year=2021, variable="B01001_001")

# merge to our data
final <- left_join(final, pop[,c("GEOID", "estimate")], by=c("ZCTA"="GEOID")) %>% 
  rename(ZCTA_pop=estimate)

# save the final list
#writexl::write_xlsx(final, "Houston_WWTP_service_ZCTAs.xlsx")
```


```{r}
# calculate population size for each WWTP
WW_pop <- final %>% 
  mutate(pop=ZCTA_pop*coverage_pct/100) %>% 
  group_by(WWTP) %>%
  summarize(Population=round(sum(pop)))
```

### Another set of WWTP maps with no WW shapefiles

```{r}
bubble_sizes <- (c(10000, 50000, 200000)/100000)
focus1 <- focus
focus1@data <- left_join(focus1@data, WW_pop, by=c("SERVICE_AR"="WWTP"))
focus1$Population <- focus1$Population/100000
m2.1<-  tm_shape(harris_shp)+ tm_polygons("grey30", alpha=0, border.col = "black", border.alpha = 1, lwd=2)+
  tm_shape(focus1) + tm_bubbles(col="Service Areas",size="Population", border.col = "black", 
                               legend.size.is.portrait =T,legend.col.is.portrait =F,legend.size.show = T,
                               scale=3,shapes.legend = 21, style="pretty",
                               shapes.legend.fill = "grey80", 
                               sizes.legend=c(0.1, 0.5, 1, 2), 
                               sizes.legend.labels=c("10k", "50k", "100k", "200k"))+
  tm_shape(dt_coor)+tm_symbols(size=0.5, shape=2,col="black", border.col ="black", border.alpha = 0.5)+tm_text("V1", size=1.5, just="bottom", ymod=1)+
  tm_add_legend('symbol', col='black', border.col='black', size=0.5, shape=2,
                label="Houston downtown",
               legend.format = list(text.align = "left"),reverse = T) +
  tm_add_legend(type = c("line"),
                col = c("black"),
                lwd = c(2),
                lty = c(1),
                labels = c("Harris County boundary"),legend.format = list(text.align = "left"))+
  tm_layout(
            inner.margins=c(0,0.1,0,0),
            legend.text.size = 0.7,
            legend.title.size=1)+
   tm_compass(position = c("right", "top"))+
  tm_scale_bar(position = c("left", "bottom"))
m2.1

tmap_save(m2.1, "Houston_6WWTP_map_circles.png", height=6, width=8,dpi=300)
```



```{r}
# for El Paso
#bubble_sizes <- (c(10000, 50000, 200000)/100000)
El_shp2$Population <- c(438446,132479,140521,113292)
El_shp2$Population <- El_shp2$Population/100000
m3.1<-   tm_shape(El_county)+ tm_polygons("grey30", alpha=0, border.col = "black", border.alpha = 1, lwd=2)+
  tm_shape(El_shp2) + tm_bubbles(col="ID",size="Population", border.col = "black", 
                               legend.size.is.portrait =T,legend.col.is.portrait =F,legend.size.show = T,
                               scale=3,shapes.legend = 21, style="pretty",#style="quantile",n=3,
                               shapes.legend.fill = "grey80", 
                               sizes.legend=c(1,5), 
                               sizes.legend.labels=c("100k", "500k"))+
  
  tm_shape(dt_coor2)+tm_symbols(size=0.5, shape=2,col="black", border.col ="black", border.alpha = 0.5)+tm_text("V1", size=1.5,just=c("right","bottom"), xmod=-1)+ # mark Downtown
  tm_add_legend('symbol', col='black', border.col='black', size=0.5, shape=2,
                label="El Paso downtown",
               legend.format = list(text.align = "left"),reverse = T) +
  tm_add_legend(type = c("line"),
                col = c("black"),
                lwd = c(2),
                lty = c(1),
                labels = c("El Paso County boundary"),legend.format = list(text.align = "left"))+
  tm_layout(
            inner.margins=c(0,0.1,0,0),
            #frame=F,
            legend.text.size = 0.7,
            legend.title.size=1)+
   tm_compass(position = c("right", "top"))+
  tm_scale_bar(position = c("left", "bottom"))
m3.1


# save the map
tmap_save(m3.1, "ElPaso_4WWTP_map_circles.png", height=6, width=8, dpi=300)


```












